const express = require('express');
const router = express.Router();
const CashRegister = require('../models/CashRegister');
const Payment = require('../models/Payment');
const Expense = require('../models/Expense');
const ActivityLog = require('../models/ActivityLog');
const User = require('../models/User');
const Student = require('../models/Student');
const bcrypt = require('bcryptjs');

// Get all cash registers with filtering
router.get('/', async (req, res) => {
  try {
    // Accept both 'institution' and 'institutionId' parameters for compatibility
    const institutionId = req.query.institution || req.query.institutionId;
    const filter = {};

    if (institutionId) filter.institution = institutionId;

    const cashRegisters = await CashRegister.find(filter)
      .populate('institution', 'name')
      .sort({ name: 1 });

    res.json(cashRegisters);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Get cash register by ID
router.get('/:id', async (req, res) => {
  try {
    const cashRegister = await CashRegister.findById(req.params.id)
      .populate('institution', 'name');

    if (!cashRegister) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }
    res.json(cashRegister);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Get cash register transactions
router.get('/:id/transactions', async (req, res) => {
  try {
    const cashRegisterId = req.params.id;

    // Get all payments for this cash register
    const payments = await Payment.find({ cashRegister: cashRegisterId })
      .populate('student', 'firstName lastName')
      .populate('course', 'name')
      .sort({ paymentDate: -1 });

    // Get all expenses for this cash register (populate related cash register for transfers)
    const expenses = await Expense.find({ cashRegister: cashRegisterId })
      .populate('relatedCashRegister', 'name')
      .sort({ expenseDate: -1 });

    // Combine and format transactions
    const transactions = [];

    // Add payments as income transactions
    payments.forEach(payment => {
      transactions.push({
        _id: payment._id,
        type: 'income',
        date: payment.paymentDate,
        amount: payment.amount,
        description: `Ödeme - ${payment.student?.firstName || ''} ${payment.student?.lastName || ''} - ${payment.course?.name || ''}`,
        category: payment.paymentType === 'creditCard' ? 'Kredi Kartı' : 'Nakit',
        relatedTo: 'Payment',
        relatedId: payment._id,
        isInvoiced: payment.isInvoiced,
        notes: payment.notes
      });
    });

    // Add expenses as expense transactions (or income if isManualIncome or transfer in)
    expenses.forEach(expense => {
      // Check if this is an income entry
      const isIncome = expense.isManualIncome === true ||
                       expense.category === 'Kasa Giriş (Manuel)' ||
                       expense.category === 'Virman (Giriş)';

      // Check if this is a transfer
      const isTransfer = expense.isTransfer === true ||
                         expense.category === 'Virman (Çıkış)' ||
                         expense.category === 'Virman (Giriş)';

      transactions.push({
        _id: expense._id,
        type: isIncome ? 'income' : 'expense',
        date: expense.expenseDate,
        amount: expense.amount,
        description: expense.description,
        category: expense.category,
        relatedTo: 'Expense',
        relatedId: expense._id,
        isAutoGenerated: expense.isAutoGenerated,
        isManualAdjustment: expense.category === 'Kasa Giriş (Manuel)' || expense.category === 'Kasa Çıkış (Manuel)',
        isTransfer: isTransfer,
        transferDirection: expense.transferDirection,
        relatedCashRegister: expense.relatedCashRegister,
        notes: expense.notes
      });
    });

    // Sort by date descending
    transactions.sort((a, b) => new Date(b.date) - new Date(a.date));

    res.json(transactions);
  } catch (error) {
    console.error('Error fetching transactions:', error);
    res.status(500).json({ message: error.message });
  }
});

// Create cash register
router.post('/', async (req, res) => {
  try {
    const cashRegister = new CashRegister(req.body);
    const newCashRegister = await cashRegister.save();

    // Log activity
    await ActivityLog.create({
      user: req.body.createdBy || 'System',
      action: 'create',
      entity: 'CashRegister',
      entityId: newCashRegister._id,
      description: `Yeni kasa oluşturuldu: ${newCashRegister.name}`,
      institution: newCashRegister.institution
    });

    const populatedCashRegister = await CashRegister.findById(newCashRegister._id)
      .populate('institution', 'name');

    res.status(201).json(populatedCashRegister);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// Update cash register
router.put('/:id', async (req, res) => {
  try {
    const cashRegister = await CashRegister.findByIdAndUpdate(
      req.params.id,
      { ...req.body, updatedBy: req.body.updatedBy },
      { new: true }
    ).populate('institution', 'name');

    if (!cashRegister) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }

    // Log activity
    await ActivityLog.create({
      user: req.body.updatedBy || 'System',
      action: 'update',
      entity: 'CashRegister',
      entityId: cashRegister._id,
      description: `Kasa güncellendi: ${cashRegister.name}`,
      institution: cashRegister.institution._id
    });

    res.json(cashRegister);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// Delete cash register
router.delete('/:id', async (req, res) => {
  try {
    const cashRegister = await CashRegister.findById(req.params.id);
    if (!cashRegister) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }

    // Check for related transactions before deletion
    const paymentCount = await Payment.countDocuments({ cashRegister: req.params.id });
    const expenseCount = await Expense.countDocuments({ cashRegister: req.params.id });

    if (paymentCount > 0 || expenseCount > 0) {
      return res.status(400).json({
        message: `Bu kasa silinemez. ${paymentCount} ödeme ve ${expenseCount} gider kaydı bulunmaktadır. Lütfen önce bu kayıtları silin veya başka bir kasaya taşıyın.`
      });
    }

    await CashRegister.findByIdAndDelete(req.params.id);

    // Log activity
    await ActivityLog.create({
      user: req.body?.deletedBy || 'System',
      action: 'delete',
      entity: 'CashRegister',
      entityId: cashRegister._id,
      description: `Kasa silindi: ${cashRegister.name}`,
      institution: cashRegister.institution
    });

    res.json({ message: 'Kasa silindi' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Adjust cash register balance manually
router.post('/:id/adjust-balance', async (req, res) => {
  try {
    const { amount, description, type, createdBy } = req.body;

    if (!amount || amount <= 0) {
      return res.status(400).json({ message: 'Geçerli bir tutar giriniz' });
    }

    if (!type || !['add', 'subtract'].includes(type)) {
      return res.status(400).json({ message: 'Geçerli bir işlem tipi seçiniz (add veya subtract)' });
    }

    const cashRegister = await CashRegister.findById(req.params.id);
    if (!cashRegister) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }

    // Determine category and whether it's income or expense
    const isIncome = type === 'add';
    const category = isIncome ? 'Kasa Giriş (Manuel)' : 'Kasa Çıkış (Manuel)';

    // Create expense record for tracking (for income, we use isManualIncome flag)
    const expenseRecord = new Expense({
      category: category,
      amount: amount,
      description: description || (isIncome ? 'Manuel bakiye ekleme' : 'Manuel bakiye çıkarma'),
      expenseDate: new Date(),
      cashRegister: cashRegister._id,
      isAutoGenerated: false,
      isManualIncome: isIncome, // Flag to indicate this is actually income
      season: cashRegister.season,
      institution: cashRegister.institution,
      createdBy: createdBy
    });
    await expenseRecord.save();

    // Update cash register balance
    // For income (add): we add to balance, but since Expense normally subtracts,
    // we need to handle this in balance calculation
    // For expense (subtract): normal expense behavior
    if (isIncome) {
      // For manual income, we add to balance (not subtract like normal expenses)
      cashRegister.balance += amount;
    } else {
      // For manual expense, balance is already handled by creating the expense
      // But since we're manually controlling this, we subtract
      cashRegister.balance -= amount;
    }
    await cashRegister.save();

    // Log activity
    await ActivityLog.create({
      user: createdBy || 'System',
      action: 'update',
      entity: 'CashRegister',
      entityId: cashRegister._id,
      description: `Kasa bakiyesi ${isIncome ? 'artırıldı' : 'azaltıldı'}: ₺${amount} - ${description || 'Açıklama yok'}`,
      institution: cashRegister.institution
    });

    const populatedCashRegister = await CashRegister.findById(cashRegister._id)
      .populate('institution', 'name');

    res.json(populatedCashRegister);
  } catch (error) {
    console.error('Error adjusting balance:', error);
    res.status(400).json({ message: error.message });
  }
});

// Transfer money between cash registers
router.post('/transfer', async (req, res) => {
  try {
    const { fromCashRegisterId, toCashRegisterId, amount, description, userId } = req.body;

    if (!fromCashRegisterId || !toCashRegisterId) {
      return res.status(400).json({ message: 'Kaynak ve hedef kasa seçilmelidir' });
    }

    if (!amount || amount <= 0) {
      return res.status(400).json({ message: 'Geçerli bir tutar giriniz' });
    }

    if (fromCashRegisterId === toCashRegisterId) {
      return res.status(400).json({ message: 'Kaynak ve hedef kasa aynı olamaz' });
    }

    const fromCash = await CashRegister.findById(fromCashRegisterId);
    const toCash = await CashRegister.findById(toCashRegisterId);

    if (!fromCash || !toCash) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }

    // Note: Negative balance allowed for transfers (same as expenses)

    fromCash.balance -= amount;
    toCash.balance += amount;

    await fromCash.save();
    await toCash.save();

    // Create expense record for the source cash register (outgoing transfer)
    const transferDate = new Date();
    const outgoingExpense = new Expense({
      category: 'Virman (Çıkış)',
      amount: amount,
      description: description || `Virman: ${fromCash.name} → ${toCash.name}`,
      expenseDate: transferDate,
      cashRegister: fromCash._id,
      isAutoGenerated: true,
      isTransfer: true,
      transferDirection: 'out',
      relatedCashRegister: toCash._id,
      season: fromCash.season,
      institution: fromCash.institution,
      createdBy: userId || 'System'
    });
    await outgoingExpense.save();

    // Create expense record for the destination cash register (incoming transfer)
    const incomingExpense = new Expense({
      category: 'Virman (Giriş)',
      amount: amount,
      description: description || `Virman: ${fromCash.name} → ${toCash.name}`,
      expenseDate: transferDate,
      cashRegister: toCash._id,
      isAutoGenerated: true,
      isManualIncome: true, // This is income, not expense
      isTransfer: true,
      transferDirection: 'in',
      relatedCashRegister: fromCash._id,
      season: toCash.season,
      institution: toCash.institution,
      createdBy: userId || 'System'
    });
    await incomingExpense.save();

    // Log activity
    await ActivityLog.create({
      user: userId || 'System',
      action: 'update',
      entity: 'CashRegister',
      description: `Virman: ${fromCash.name} → ${toCash.name}: ₺${amount} - ${description || 'Açıklama yok'}`,
      institution: fromCash.institution
    });

    const populatedFromCash = await CashRegister.findById(fromCash._id)
      .populate('institution', 'name');
    const populatedToCash = await CashRegister.findById(toCash._id)
      .populate('institution', 'name');

    res.json({ fromCash: populatedFromCash, toCash: populatedToCash });
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// Delete transaction (Payment or Expense) with admin approval
// This endpoint handles all scenarios:
// - Payment deletion: reverses cash register, student balance, deletes related expenses (VAT, commission)
// - Expense deletion: reverses cash register, handles refund expenses and auto-generated expenses
router.post('/transactions/:id/delete', async (req, res) => {
  try {
    const { password, transactionType, userId } = req.body;
    const transactionId = req.params.id;

    // Verify admin password - must explicitly select password field
    const user = await User.findById(userId).select('+password');
    if (!user) {
      return res.status(404).json({ message: 'Kullanıcı bulunamadı' });
    }

    const isPasswordValid = await bcrypt.compare(password, user.password);
    if (!isPasswordValid) {
      return res.status(401).json({ message: 'Hatalı şifre' });
    }

    if (user.role !== 'superadmin' && user.role !== 'admin') {
      return res.status(403).json({ message: 'Bu işlem için admin yetkisi gereklidir' });
    }

    let transaction;
    let cashRegister;
    let description;
    const deletionDetails = [];

    if (transactionType === 'Payment') {
      transaction = await Payment.findById(transactionId)
        .populate('student', 'firstName lastName')
        .populate('course', 'name');

      if (!transaction) {
        return res.status(404).json({ message: 'Ödeme kaydı bulunamadı' });
      }

      // Check if this payment is refunded - we can still delete but need to handle differently
      if (transaction.isRefunded) {
        // Find and delete the refund expense too
        const refundExpense = await Expense.findOne({
          relatedPayment: transactionId,
          category: 'Ödeme İadesi'
        });

        if (refundExpense) {
          // The refund expense subtracted from cash register, so we need to add it back
          await CashRegister.findByIdAndUpdate(refundExpense.cashRegister, {
            $inc: { balance: refundExpense.amount }
          });
          await Expense.findByIdAndDelete(refundExpense._id);
          deletionDetails.push(`İade gideri silindi ve kasaya ₺${refundExpense.amount} eklendi`);
        }
      }

      cashRegister = await CashRegister.findById(transaction.cashRegister);

      // 1. Reverse cash register balance (subtract payment amount from cash register)
      cashRegister.balance -= transaction.amount;
      await cashRegister.save();
      deletionDetails.push(`Kasadan ₺${transaction.amount} düşüldü`);

      // 2. Find and delete related auto-generated expenses (VAT, Commission)
      const relatedExpenses = await Expense.find({
        relatedPayment: transactionId,
        isAutoGenerated: true,
        category: { $in: ['KDV', 'Kredi Kartı Komisyonu'] }
      });

      for (const expense of relatedExpenses) {
        // These expenses subtracted from cash register, so we add them back
        await CashRegister.findByIdAndUpdate(expense.cashRegister, {
          $inc: { balance: expense.amount }
        });
        await Expense.findByIdAndDelete(expense._id);
        deletionDetails.push(`${expense.category} gideri silindi ve kasaya ₺${expense.amount} eklendi`);
      }

      // 3. Reverse student balance (add back debt) - only if payment was NOT refunded
      // IMPORTANT: If payment was refunded, the refund operation already added debt back to student balance
      // So we should NOT add debt again when deleting a refunded payment
      if (transaction.student && transaction.student._id && !transaction.isRefunded) {
        try {
          const student = await Student.findById(transaction.student._id);
          if (student) {
            student.balance += transaction.amount;
            await student.save();
            deletionDetails.push(`Öğrenci bakiyesine ₺${transaction.amount} borç eklendi`);
          }
        } catch (error) {
          console.log('Student not found, skipping balance update:', error.message);
        }
      } else if (transaction.isRefunded) {
        deletionDetails.push(`Öğrenci bakiyesi değiştirilmedi (ödeme zaten iade edilmişti)`);
      }

      // 4. If payment is linked to a payment plan, reset the installment status
      if (transaction.paymentPlan) {
        try {
          const PaymentPlan = require('../models/PaymentPlan');
          const paymentPlan = await PaymentPlan.findById(transaction.paymentPlan);

          if (paymentPlan && paymentPlan.installments) {
            // Find the installment that matches this payment
            const installmentIndex = paymentPlan.installments.findIndex(
              inst => inst.paymentId && inst.paymentId.toString() === transactionId
            );

            if (installmentIndex !== -1) {
              // Reset installment to pending
              paymentPlan.installments[installmentIndex].status = 'pending';
              paymentPlan.installments[installmentIndex].paidAmount = 0;
              paymentPlan.installments[installmentIndex].paidDate = null;
              paymentPlan.installments[installmentIndex].paymentId = null;

              // Recalculate paid amount
              let totalPaid = 0;
              for (const inst of paymentPlan.installments) {
                if (inst.status === 'paid') {
                  totalPaid += inst.paidAmount || inst.amount || 0;
                }
              }
              paymentPlan.paidAmount = totalPaid;
              paymentPlan.remainingAmount = paymentPlan.totalAmount - totalPaid;

              // Update status
              if (totalPaid === 0) {
                paymentPlan.status = 'pending';
              } else if (totalPaid < paymentPlan.totalAmount) {
                paymentPlan.status = 'partial';
              }

              await paymentPlan.save();
              deletionDetails.push(`Ödeme planı taksiti 'bekliyor' durumuna döndürüldü`);
            }
          }
        } catch (error) {
          console.log('Error updating payment plan:', error.message);
        }
      }

      const studentName = transaction.student
        ? `${transaction.student.firstName} ${transaction.student.lastName}`
        : 'Silinmiş Öğrenci';
      const courseName = transaction.course?.name || 'Silinmiş Ders';

      description = `Ödeme silindi: ${studentName} - ${courseName} - ₺${transaction.amount}`;

      await Payment.findByIdAndDelete(transactionId);

    } else if (transactionType === 'Expense') {
      transaction = await Expense.findById(transactionId);

      if (!transaction) {
        return res.status(404).json({ message: 'Gider kaydı bulunamadı' });
      }

      cashRegister = await CashRegister.findById(transaction.cashRegister);

      // Special handling for different expense types

      // 1. If it's a refund expense, reset the related payment's refund status
      if (transaction.category === 'Ödeme İadesi' && transaction.relatedPayment) {
        const relatedPayment = await Payment.findById(transaction.relatedPayment);
        if (relatedPayment) {
          // Reset payment's refund status
          relatedPayment.isRefunded = false;
          relatedPayment.refundDate = null;
          relatedPayment.refundAmount = null;
          relatedPayment.refundCashRegister = null;
          relatedPayment.status = 'completed';
          await relatedPayment.save();

          // The refund had added to student's balance, so we need to subtract
          if (relatedPayment.student) {
            await Student.findByIdAndUpdate(relatedPayment.student, {
              $inc: { balance: -transaction.amount }
            });
            deletionDetails.push(`Öğrenci bakiyesinden ₺${transaction.amount} düşüldü (iade iptal)`);
          }

          deletionDetails.push(`İlişkili ödemenin iade durumu sıfırlandı`);
        }
      }

      // 2. If it's an auto-generated KDV or Commission expense, warn but still delete
      if (transaction.isAutoGenerated && ['KDV', 'Kredi Kartı Komisyonu'].includes(transaction.category)) {
        deletionDetails.push(`Uyarı: Bu otomatik oluşturulmuş bir ${transaction.category} gideriydi`);
      }

      // Reverse cash register balance (add back expense amount)
      cashRegister.balance += transaction.amount;
      await cashRegister.save();
      deletionDetails.push(`Kasaya ₺${transaction.amount} eklendi`);

      description = `Gider silindi: ${transaction.category} - ${transaction.description} - ₺${transaction.amount}`;

      await Expense.findByIdAndDelete(transactionId);
    } else {
      return res.status(400).json({ message: 'Geçersiz işlem tipi' });
    }

    // Log activity
    await ActivityLog.create({
      user: user.username,
      action: 'delete',
      entity: transactionType,
      entityId: transactionId,
      description: description + ' | Detaylar: ' + deletionDetails.join(', '),
      institution: cashRegister.institution
    });

    res.json({
      message: 'Hareket başarıyla silindi ve kasa bakiyesi güncellendi',
      details: deletionDetails,
      cashRegister: await CashRegister.findById(cashRegister._id).populate('institution', 'name')
    });
  } catch (error) {
    console.error('Error deleting transaction:', error);
    res.status(500).json({ message: error.message });
  }
});

module.exports = router;
