const express = require('express');
const router = express.Router();
const CashRegister = require('../models/CashRegister');
const Payment = require('../models/Payment');
const Expense = require('../models/Expense');
const ActivityLog = require('../models/ActivityLog');
const User = require('../models/User');
const Student = require('../models/Student');
const bcrypt = require('bcryptjs');

// Get all cash registers with filtering
router.get('/', async (req, res) => {
  try {
    const { institutionId } = req.query;
    const filter = {};

    if (institutionId) filter.institution = institutionId;

    const cashRegisters = await CashRegister.find(filter)
      .populate('institution', 'name')
      .sort({ name: 1 });

    res.json(cashRegisters);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Get cash register by ID
router.get('/:id', async (req, res) => {
  try {
    const cashRegister = await CashRegister.findById(req.params.id)
      .populate('institution', 'name');

    if (!cashRegister) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }
    res.json(cashRegister);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Get cash register transactions
router.get('/:id/transactions', async (req, res) => {
  try {
    const cashRegisterId = req.params.id;

    // Get all payments for this cash register
    const payments = await Payment.find({ cashRegister: cashRegisterId })
      .populate('student', 'firstName lastName')
      .populate('course', 'name')
      .sort({ paymentDate: -1 });

    // Get all expenses for this cash register
    const expenses = await Expense.find({ cashRegister: cashRegisterId })
      .sort({ expenseDate: -1 });

    // Combine and format transactions
    const transactions = [];

    // Add payments as income transactions
    payments.forEach(payment => {
      transactions.push({
        _id: payment._id,
        type: 'income',
        date: payment.paymentDate,
        amount: payment.amount,
        description: `Ödeme - ${payment.student?.firstName || ''} ${payment.student?.lastName || ''} - ${payment.course?.name || ''}`,
        category: payment.paymentType === 'creditCard' ? 'Kredi Kartı' : 'Nakit',
        relatedTo: 'Payment',
        relatedId: payment._id,
        isInvoiced: payment.isInvoiced,
        notes: payment.notes
      });
    });

    // Add expenses as expense transactions
    expenses.forEach(expense => {
      transactions.push({
        _id: expense._id,
        type: 'expense',
        date: expense.expenseDate,
        amount: expense.amount,
        description: expense.description,
        category: expense.category,
        relatedTo: 'Expense',
        relatedId: expense._id,
        isAutoGenerated: expense.isAutoGenerated,
        notes: expense.notes
      });
    });

    // Sort by date descending
    transactions.sort((a, b) => new Date(b.date) - new Date(a.date));

    res.json(transactions);
  } catch (error) {
    console.error('Error fetching transactions:', error);
    res.status(500).json({ message: error.message });
  }
});

// Create cash register
router.post('/', async (req, res) => {
  try {
    const cashRegister = new CashRegister(req.body);
    const newCashRegister = await cashRegister.save();

    // Log activity
    await ActivityLog.create({
      user: req.body.createdBy || 'System',
      action: 'create',
      entity: 'CashRegister',
      entityId: newCashRegister._id,
      description: `Yeni kasa oluşturuldu: ${newCashRegister.name}`,
      institution: newCashRegister.institution
    });

    const populatedCashRegister = await CashRegister.findById(newCashRegister._id)
      .populate('institution', 'name');

    res.status(201).json(populatedCashRegister);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// Update cash register
router.put('/:id', async (req, res) => {
  try {
    const cashRegister = await CashRegister.findByIdAndUpdate(
      req.params.id,
      { ...req.body, updatedBy: req.body.updatedBy },
      { new: true }
    ).populate('institution', 'name');

    if (!cashRegister) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }

    // Log activity
    await ActivityLog.create({
      user: req.body.updatedBy || 'System',
      action: 'update',
      entity: 'CashRegister',
      entityId: cashRegister._id,
      description: `Kasa güncellendi: ${cashRegister.name}`,
      institution: cashRegister.institution._id
    });

    res.json(cashRegister);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// Delete cash register
router.delete('/:id', async (req, res) => {
  try {
    const cashRegister = await CashRegister.findById(req.params.id);
    if (!cashRegister) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }

    // Check for related transactions before deletion
    const paymentCount = await Payment.countDocuments({ cashRegister: req.params.id });
    const expenseCount = await Expense.countDocuments({ cashRegister: req.params.id });

    if (paymentCount > 0 || expenseCount > 0) {
      return res.status(400).json({
        message: `Bu kasa silinemez. ${paymentCount} ödeme ve ${expenseCount} gider kaydı bulunmaktadır. Lütfen önce bu kayıtları silin veya başka bir kasaya taşıyın.`
      });
    }

    await CashRegister.findByIdAndDelete(req.params.id);

    // Log activity
    await ActivityLog.create({
      user: req.body?.deletedBy || 'System',
      action: 'delete',
      entity: 'CashRegister',
      entityId: cashRegister._id,
      description: `Kasa silindi: ${cashRegister.name}`,
      institution: cashRegister.institution
    });

    res.json({ message: 'Kasa silindi' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Adjust cash register balance manually
router.post('/:id/adjust-balance', async (req, res) => {
  try {
    const { amount, description, type, userId } = req.body;

    if (!amount || amount <= 0) {
      return res.status(400).json({ message: 'Geçerli bir tutar giriniz' });
    }

    if (!type || !['add', 'subtract'].includes(type)) {
      return res.status(400).json({ message: 'Geçerli bir işlem tipi seçiniz (add veya subtract)' });
    }

    const cashRegister = await CashRegister.findById(req.params.id);
    if (!cashRegister) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }

    const adjustAmount = type === 'add' ? amount : -amount;
    cashRegister.balance += adjustAmount;
    await cashRegister.save();

    // Log activity
    await ActivityLog.create({
      user: userId || 'System',
      action: 'update',
      entity: 'CashRegister',
      entityId: cashRegister._id,
      description: `Kasa bakiyesi ${type === 'add' ? 'artırıldı' : 'azaltıldı'}: ₺${amount} - ${description || 'Açıklama yok'}`,
      institution: cashRegister.institution
    });

    const populatedCashRegister = await CashRegister.findById(cashRegister._id)
      .populate('institution', 'name');

    res.json(populatedCashRegister);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// Transfer money between cash registers
router.post('/transfer', async (req, res) => {
  try {
    const { fromCashRegisterId, toCashRegisterId, amount, description, userId } = req.body;

    if (!fromCashRegisterId || !toCashRegisterId) {
      return res.status(400).json({ message: 'Kaynak ve hedef kasa seçilmelidir' });
    }

    if (!amount || amount <= 0) {
      return res.status(400).json({ message: 'Geçerli bir tutar giriniz' });
    }

    if (fromCashRegisterId === toCashRegisterId) {
      return res.status(400).json({ message: 'Kaynak ve hedef kasa aynı olamaz' });
    }

    const fromCash = await CashRegister.findById(fromCashRegisterId);
    const toCash = await CashRegister.findById(toCashRegisterId);

    if (!fromCash || !toCash) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }

    if (fromCash.balance < amount) {
      return res.status(400).json({ message: 'Yetersiz bakiye' });
    }

    fromCash.balance -= amount;
    toCash.balance += amount;

    await fromCash.save();
    await toCash.save();

    // Log activity
    await ActivityLog.create({
      user: userId || 'System',
      action: 'update',
      entity: 'CashRegister',
      description: `Virman: ${fromCash.name} → ${toCash.name}: ₺${amount} - ${description || 'Açıklama yok'}`,
      institution: fromCash.institution
    });

    const populatedFromCash = await CashRegister.findById(fromCash._id)
      .populate('institution', 'name');
    const populatedToCash = await CashRegister.findById(toCash._id)
      .populate('institution', 'name');

    res.json({ fromCash: populatedFromCash, toCash: populatedToCash });
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// Delete transaction (Payment or Expense) with admin approval
router.post('/transactions/:id/delete', async (req, res) => {
  try {
    const { password, transactionType, userId } = req.body;
    const transactionId = req.params.id;

    // Verify admin password - must explicitly select password field
    const user = await User.findById(userId).select('+password');
    if (!user) {
      return res.status(404).json({ message: 'Kullanıcı bulunamadı' });
    }

    const isPasswordValid = await bcrypt.compare(password, user.password);
    if (!isPasswordValid) {
      return res.status(401).json({ message: 'Hatalı şifre' });
    }

    if (user.role !== 'superadmin' && user.role !== 'admin') {
      return res.status(403).json({ message: 'Bu işlem için admin yetkisi gereklidir' });
    }

    let transaction;
    let cashRegister;
    let description;

    if (transactionType === 'Payment') {
      transaction = await Payment.findById(transactionId)
        .populate('student', 'firstName lastName')
        .populate('course', 'name');

      if (!transaction) {
        return res.status(404).json({ message: 'Ödeme kaydı bulunamadı' });
      }

      if (transaction.isRefunded) {
        return res.status(400).json({ message: 'İade edilmiş ödeme silinemez' });
      }

      cashRegister = await CashRegister.findById(transaction.cashRegister);

      // Reverse cash register balance (subtract payment amount)
      cashRegister.balance -= transaction.amount;
      await cashRegister.save();

      // Reverse student balance (add back debt) - only if student still exists
      if (transaction.student && transaction.student._id) {
        try {
          await Student.findByIdAndUpdate(transaction.student._id, {
            $inc: { balance: transaction.amount }
          });
        } catch (error) {
          console.log('Student not found, skipping balance update:', error.message);
        }
      }

      const studentName = transaction.student
        ? `${transaction.student.firstName} ${transaction.student.lastName}`
        : 'Silinmiş Öğrenci';
      const courseName = transaction.course?.name || 'Silinmiş Ders';

      description = `Ödeme silindi: ${studentName} - ${courseName} - ₺${transaction.amount}`;

      await Payment.findByIdAndDelete(transactionId);

    } else if (transactionType === 'Expense') {
      transaction = await Expense.findById(transactionId);

      if (!transaction) {
        return res.status(404).json({ message: 'Gider kaydı bulunamadı' });
      }

      cashRegister = await CashRegister.findById(transaction.cashRegister);

      // Reverse cash register balance (add back expense amount)
      cashRegister.balance += transaction.amount;
      await cashRegister.save();

      description = `Gider silindi: ${transaction.category} - ${transaction.description} - ₺${transaction.amount}`;

      await Expense.findByIdAndDelete(transactionId);
    } else {
      return res.status(400).json({ message: 'Geçersiz işlem tipi' });
    }

    // Log activity
    await ActivityLog.create({
      user: user.username,
      action: 'delete',
      entity: transactionType,
      entityId: transactionId,
      description: description,
      institution: cashRegister.institution
    });

    res.json({
      message: 'Hareket başarıyla silindi ve kasa bakiyesi güncellendi',
      cashRegister: await CashRegister.findById(cashRegister._id).populate('institution', 'name')
    });
  } catch (error) {
    console.error('Error deleting transaction:', error);
    res.status(500).json({ message: error.message });
  }
});

module.exports = router;
