const express = require('express');
const router = express.Router();
const PaymentPlan = require('../models/PaymentPlan');
const Payment = require('../models/Payment');
const Expense = require('../models/Expense');
const CashRegister = require('../models/CashRegister');
const Student = require('../models/Student');
const ActivityLog = require('../models/ActivityLog');

// Get all payment plans with filtering
router.get('/', async (req, res) => {
  try {
    const { institutionId, seasonId, studentId } = req.query;
    const filter = {};

    if (institutionId) filter.institution = institutionId;
    if (seasonId) filter.season = seasonId;
    if (studentId) filter.student = studentId;

    const paymentPlans = await PaymentPlan.find(filter)
      .populate('institution', 'name')
      .populate('season', 'name startDate endDate')
      .populate('student', 'firstName lastName')
      .populate('course', 'name')
      .sort({ createdAt: -1 });

    res.json(paymentPlans);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Get payment plan by ID
router.get('/:id', async (req, res) => {
  try {
    const paymentPlan = await PaymentPlan.findById(req.params.id)
      .populate('institution', 'name')
      .populate('season', 'name startDate endDate')
      .populate('student', 'firstName lastName')
      .populate('course', 'name');

    if (!paymentPlan) {
      return res.status(404).json({ message: 'Ödeme planı bulunamadı' });
    }
    res.json(paymentPlan);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Create payment plan
router.post('/', async (req, res) => {
  try {
    // Validate foreign keys
    if (req.body.student) {
      const studentExists = await Student.exists({ _id: req.body.student });
      if (!studentExists) {
        return res.status(404).json({ message: 'Öğrenci bulunamadı' });
      }
    }

    if (req.body.cashRegister) {
      const cashRegisterExists = await CashRegister.exists({ _id: req.body.cashRegister });
      if (!cashRegisterExists) {
        return res.status(404).json({ message: 'Kasa bulunamadı' });
      }
    }

    // Set pending status for future credit card payments
    const paymentPlanData = {
      ...req.body,
      isPendingPayment: req.body.paymentType === 'creditCard' && !req.body.autoCreatePayment
    };

    const paymentPlan = new PaymentPlan(paymentPlanData);
    const newPaymentPlan = await paymentPlan.save();

    // Update student balance - add debt when payment plan is created
    await Student.findByIdAndUpdate(req.body.student, {
      $inc: { balance: req.body.discountedAmount }
    });

    // If credit card payment and payment date is today, auto-create payment and expenses
    if (req.body.autoCreatePayment && req.body.paymentType === 'creditCard') {
      const student = await Student.findById(req.body.student);
      const chargeAmount = req.body.discountedAmount;

      // Create payment (only if autoCreatePayment is true, meaning payment date is today)
      const payment = new Payment({
        student: req.body.student,
        course: req.body.course,
        enrollment: req.body.enrollment,
        paymentPlan: newPaymentPlan._id,
        paymentType: 'creditCard',
        paymentMethod: 'creditCard',
        amount: chargeAmount,
        netAmount: chargeAmount,
        creditCardCommission: req.body.creditCardCommission,
        creditCardInstallments: req.body.creditCardInstallments,
        vat: req.body.vat,
        isInvoiced: req.body.isInvoiced,
        cashRegister: req.body.cashRegister,
        paymentDate: req.body.paymentDate ? new Date(req.body.paymentDate) : new Date(),
        season: req.body.season,
        institution: req.body.institution,
        status: 'completed',
        notes: `Kredi kartı ödemesi - ${req.body.creditCardInstallments} taksit`,
        createdBy: req.body.createdBy
      });

      const savedPayment = await payment.save();

      // Update cash register balance
      await CashRegister.findByIdAndUpdate(req.body.cashRegister, {
        $inc: { balance: chargeAmount }
      });

      // Update student balance - subtract payment (balance was already increased above)
      await Student.findByIdAndUpdate(req.body.student, {
        $inc: { balance: -chargeAmount }
      });

      // Create commission expense
      if (req.body.creditCardCommission && req.body.creditCardCommission.amount > 0) {
        const commissionExpense = new Expense({
          category: 'Kredi Kartı Komisyonu',
          amount: req.body.creditCardCommission.amount,
          description: `${student.firstName} ${student.lastName} - ${req.body.creditCardInstallments} Taksit (%${req.body.creditCardCommission.rate})`,
          expenseDate: new Date(),
          cashRegister: req.body.cashRegister,
          isAutoGenerated: true,
          relatedPayment: savedPayment._id,
          relatedStudent: req.body.student,
          season: req.body.season,
          institution: req.body.institution,
          createdBy: req.body.createdBy
        });

        await commissionExpense.save();

        // Deduct commission from cash register
        await CashRegister.findByIdAndUpdate(req.body.cashRegister, {
          $inc: { balance: -req.body.creditCardCommission.amount }
        });
      }

      // Create VAT expense if invoiced
      if (req.body.isInvoiced && req.body.vat && req.body.vat.amount > 0) {
        const vatExpense = new Expense({
          category: 'KDV',
          amount: req.body.vat.amount,
          description: `${student.firstName} ${student.lastName} - ${chargeAmount.toFixed(2)} TL üzerinden %${req.body.vat.rate} KDV`,
          expenseDate: new Date(),
          cashRegister: req.body.cashRegister,
          isAutoGenerated: true,
          relatedPayment: savedPayment._id,
          relatedStudent: req.body.student,
          season: req.body.season,
          institution: req.body.institution,
          createdBy: req.body.createdBy
        });

        await vatExpense.save();

        // Deduct VAT from cash register
        await CashRegister.findByIdAndUpdate(req.body.cashRegister, {
          $inc: { balance: -req.body.vat.amount }
        });
      }

      // Mark all installments as paid
      newPaymentPlan.installments.forEach(inst => {
        inst.isPaid = true;
        inst.paidAmount = inst.amount;
        inst.paidDate = new Date();
      });
      newPaymentPlan.paidAmount = chargeAmount;
      newPaymentPlan.isCompleted = true;
      await newPaymentPlan.save();
    }

    // Log activity
    await ActivityLog.create({
      user: req.body.createdBy || 'System',
      action: 'create',
      entity: 'PaymentPlan',
      entityId: newPaymentPlan._id,
      description: `Yeni ödeme planı oluşturuldu`,
      institution: newPaymentPlan.institution,
      season: newPaymentPlan.season
    });

    const populatedPaymentPlan = await PaymentPlan.findById(newPaymentPlan._id)
      .populate('institution', 'name')
      .populate('season', 'name startDate endDate')
      .populate('student', 'firstName lastName')
      .populate('course', 'name');

    res.status(201).json(populatedPaymentPlan);
  } catch (error) {
    console.error('Error creating payment plan:', error);
    res.status(400).json({ message: error.message });
  }
});

// Update payment plan
router.put('/:id', async (req, res) => {
  try {
    const paymentPlan = await PaymentPlan.findByIdAndUpdate(
      req.params.id,
      { ...req.body, updatedBy: req.body.updatedBy },
      { new: true }
    ).populate('institution', 'name')
     .populate('season', 'name startDate endDate')
     .populate('student', 'firstName lastName')
     .populate('course', 'name');

    if (!paymentPlan) {
      return res.status(404).json({ message: 'Ödeme planı bulunamadı' });
    }

    // Log activity
    await ActivityLog.create({
      user: req.body.updatedBy || 'System',
      action: 'update',
      entity: 'PaymentPlan',
      entityId: paymentPlan._id,
      description: `Ödeme planı güncellendi`,
      institution: paymentPlan.institution._id,
      season: paymentPlan.season._id
    });

    res.json(paymentPlan);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// Process pending credit card payment
router.post('/:id/process-credit-card-payment', async (req, res) => {
  try {
    const { cashRegisterId, createdBy } = req.body;

    const paymentPlan = await PaymentPlan.findById(req.params.id)
      .populate('student', 'firstName lastName');

    if (!paymentPlan) {
      return res.status(404).json({ message: 'Ödeme planı bulunamadı' });
    }

    if (paymentPlan.paymentType !== 'creditCard') {
      return res.status(400).json({ message: 'Bu ödeme planı kredi kartı ödemesi değil' });
    }

    if (!paymentPlan.isPendingPayment) {
      return res.status(400).json({ message: 'Bu ödeme zaten işlenmiş' });
    }

    const chargeAmount = paymentPlan.discountedAmount;
    const student = paymentPlan.student;

    // Create payment
    const payment = new Payment({
      student: paymentPlan.student._id,
      course: paymentPlan.course,
      enrollment: paymentPlan.enrollment,
      paymentPlan: paymentPlan._id,
      paymentType: 'creditCard',
      paymentMethod: 'creditCard',
      amount: chargeAmount,
      netAmount: chargeAmount,
      creditCardCommission: paymentPlan.creditCardCommission,
      creditCardInstallments: paymentPlan.creditCardInstallments,
      vat: paymentPlan.vat,
      isInvoiced: paymentPlan.isInvoiced,
      cashRegister: cashRegisterId,
      paymentDate: new Date(),
      season: paymentPlan.season,
      institution: paymentPlan.institution,
      status: 'completed',
      notes: `Kredi kartı ödemesi - ${paymentPlan.creditCardInstallments} taksit`,
      createdBy: createdBy
    });

    const savedPayment = await payment.save();

    // Update cash register balance
    await CashRegister.findByIdAndUpdate(cashRegisterId, {
      $inc: { balance: chargeAmount }
    });

    // Update student balance
    await Student.findByIdAndUpdate(paymentPlan.student._id, {
      $inc: { balance: -chargeAmount }
    });

    // Create commission expense
    if (paymentPlan.creditCardCommission && paymentPlan.creditCardCommission.amount > 0) {
      const commissionExpense = new Expense({
        category: 'Kredi Kartı Komisyonu',
        amount: paymentPlan.creditCardCommission.amount,
        description: `${student.firstName} ${student.lastName} - ${paymentPlan.creditCardInstallments} Taksit (%${paymentPlan.creditCardCommission.rate})`,
        expenseDate: new Date(),
        cashRegister: cashRegisterId,
        isAutoGenerated: true,
        relatedPayment: savedPayment._id,
        relatedStudent: paymentPlan.student._id,
        season: paymentPlan.season,
        institution: paymentPlan.institution,
        createdBy: createdBy
      });

      await commissionExpense.save();

      // Deduct commission from cash register
      await CashRegister.findByIdAndUpdate(cashRegisterId, {
        $inc: { balance: -paymentPlan.creditCardCommission.amount }
      });
    }

    // Create VAT expense if invoiced
    if (paymentPlan.isInvoiced && paymentPlan.vat && paymentPlan.vat.amount > 0) {
      const vatExpense = new Expense({
        category: 'KDV',
        amount: paymentPlan.vat.amount,
        description: `${student.firstName} ${student.lastName} - ${chargeAmount.toFixed(2)} TL üzerinden %${paymentPlan.vat.rate} KDV`,
        expenseDate: new Date(),
        cashRegister: cashRegisterId,
        isAutoGenerated: true,
        relatedPayment: savedPayment._id,
        relatedStudent: paymentPlan.student._id,
        season: paymentPlan.season,
        institution: paymentPlan.institution,
        createdBy: createdBy
      });

      await vatExpense.save();

      // Deduct VAT from cash register
      await CashRegister.findByIdAndUpdate(cashRegisterId, {
        $inc: { balance: -paymentPlan.vat.amount }
      });
    }

    // Mark installment as paid
    paymentPlan.installments.forEach(inst => {
      inst.isPaid = true;
      inst.paidAmount = inst.amount;
      inst.paidDate = new Date();
    });

    // Update payment plan
    paymentPlan.paidAmount = chargeAmount;
    paymentPlan.isCompleted = true;
    paymentPlan.isPendingPayment = false;
    await paymentPlan.save();

    // Log activity
    await ActivityLog.create({
      user: createdBy || 'System',
      action: 'update',
      entity: 'PaymentPlan',
      entityId: paymentPlan._id,
      description: `Bekleyen kredi kartı ödemesi işlendi (${chargeAmount} TL)`,
      institution: paymentPlan.institution,
      season: paymentPlan.season
    });

    const populatedPaymentPlan = await PaymentPlan.findById(paymentPlan._id)
      .populate('institution', 'name')
      .populate('season', 'name startDate endDate')
      .populate('student', 'firstName lastName')
      .populate('course', 'name');

    res.json(populatedPaymentPlan);
  } catch (error) {
    console.error('Error processing credit card payment:', error);
    res.status(400).json({ message: error.message });
  }
});

// Pay installment (for cash and credit card installment payments)
router.post('/:id/pay-installment', async (req, res) => {
  try {
    const { installmentNumber, amount, cashRegisterId, isInvoiced, paymentDate, vatRate } = req.body;

    const paymentPlan = await PaymentPlan.findById(req.params.id)
      .populate('student', 'firstName lastName');

    if (!paymentPlan) {
      return res.status(404).json({ message: 'Ödeme planı bulunamadı' });
    }

    const installment = paymentPlan.installments.find(
      inst => inst.installmentNumber === installmentNumber
    );

    if (!installment) {
      return res.status(404).json({ message: 'Taksit bulunamadı' });
    }

    // Determine if this is a credit card payment
    const isCreditCardPayment = paymentPlan.paymentType === 'creditCard';

    // Create payment
    const payment = new Payment({
      student: paymentPlan.student._id,
      course: paymentPlan.course,
      enrollment: paymentPlan.enrollment,
      paymentPlan: paymentPlan._id,
      paymentType: isCreditCardPayment ? 'creditCard' : 'cash',
      amount: amount,
      netAmount: amount,
      isInvoiced: isInvoiced,
      cashRegister: cashRegisterId,
      paymentDate: paymentDate || new Date(),
      installmentNumber: installmentNumber,
      season: paymentPlan.season,
      institution: paymentPlan.institution,
      notes: `${installmentNumber}. taksit ödemesi`,
      createdBy: req.body.createdBy
    });

    // Add credit card info if applicable
    if (isCreditCardPayment && paymentPlan.creditCardCommission) {
      payment.creditCardCommission = paymentPlan.creditCardCommission;
      payment.creditCardInstallments = paymentPlan.creditCardInstallments;
    }

    const savedPayment = await payment.save();

    // Update cash register balance
    await CashRegister.findByIdAndUpdate(cashRegisterId, {
      $inc: { balance: amount }
    });

    // Update student balance
    await Student.findByIdAndUpdate(paymentPlan.student._id, {
      $inc: { balance: -amount }
    });

    // Create credit card commission expense if this is a credit card payment
    if (isCreditCardPayment && paymentPlan.creditCardCommission && paymentPlan.creditCardCommission.amount > 0) {
      const commissionAmount = paymentPlan.creditCardCommission.amount;
      const commissionExpense = new Expense({
        category: 'Kredi Kartı Komisyonu',
        amount: commissionAmount,
        description: `${paymentPlan.student.firstName} ${paymentPlan.student.lastName} - ${installmentNumber}. taksit ${paymentPlan.creditCardInstallments} Taksit (%${paymentPlan.creditCardCommission.rate})`,
        expenseDate: paymentDate || new Date(),
        cashRegister: cashRegisterId,
        isAutoGenerated: true,
        relatedPayment: savedPayment._id,
        relatedStudent: paymentPlan.student._id,
        season: paymentPlan.season,
        institution: paymentPlan.institution,
        createdBy: req.body.createdBy
      });

      await commissionExpense.save();

      // Deduct commission from cash register
      await CashRegister.findByIdAndUpdate(cashRegisterId, {
        $inc: { balance: -commissionAmount }
      });
    }

    // Create VAT expense if invoiced
    if (isInvoiced && vatRate) {
      const vatAmount = (amount * vatRate) / 100;
      const vatExpense = new Expense({
        category: 'KDV',
        amount: vatAmount,
        description: `${paymentPlan.student.firstName} ${paymentPlan.student.lastName} - ${installmentNumber}. taksit ${amount.toFixed(2)} TL üzerinden %${vatRate} KDV`,
        expenseDate: paymentDate || new Date(),
        cashRegister: cashRegisterId,
        isAutoGenerated: true,
        relatedPayment: savedPayment._id,
        relatedStudent: paymentPlan.student._id,
        season: paymentPlan.season,
        institution: paymentPlan.institution,
        createdBy: req.body.createdBy
      });

      await vatExpense.save();

      // Deduct VAT from cash register
      await CashRegister.findByIdAndUpdate(cashRegisterId, {
        $inc: { balance: -vatAmount }
      });
    }

    // Update installment
    installment.isPaid = true;
    installment.paidAmount = amount;
    installment.paidDate = paymentDate || new Date();
    installment.isInvoiced = isInvoiced;

    // Update payment plan totals
    paymentPlan.paidAmount = (paymentPlan.paidAmount || 0) + amount;
    paymentPlan.remainingAmount = paymentPlan.discountedAmount - paymentPlan.paidAmount;

    // Check if all installments are paid
    const allPaid = paymentPlan.installments.every(inst => inst.isPaid);
    if (allPaid) {
      paymentPlan.isCompleted = true;
    }

    await paymentPlan.save();

    // Log activity
    await ActivityLog.create({
      user: req.body.createdBy || 'System',
      action: 'update',
      entity: 'PaymentPlan',
      entityId: paymentPlan._id,
      description: `${installmentNumber}. taksit ödendi (${amount} TL)`,
      institution: paymentPlan.institution,
      season: paymentPlan.season
    });

    const populatedPaymentPlan = await PaymentPlan.findById(paymentPlan._id)
      .populate('institution', 'name')
      .populate('season', 'name startDate endDate')
      .populate('student', 'firstName lastName')
      .populate('course', 'name');

    res.json(populatedPaymentPlan);
  } catch (error) {
    console.error('Error paying installment:', error);
    res.status(400).json({ message: error.message });
  }
});

// Delete payment plan
router.delete('/:id', async (req, res) => {
  try {
    const paymentPlan = await PaymentPlan.findById(req.params.id);
    if (!paymentPlan) {
      return res.status(404).json({ message: 'Ödeme planı bulunamadı' });
    }

    // Clean up related records before deleting payment plan
    // 1. Find and delete all related payments
    const relatedPayments = await Payment.find({ paymentPlan: paymentPlan._id });
    for (const payment of relatedPayments) {
      // Revert cash register balance
      if (payment.cashRegister) {
        await CashRegister.findByIdAndUpdate(payment.cashRegister, {
          $inc: { balance: -payment.amount }
        });
      }

      // Revert student balance
      if (payment.student) {
        await Student.findByIdAndUpdate(payment.student, {
          $inc: { balance: payment.amount }
        });
      }

      // Delete related expenses (commission, VAT)
      const paymentExpenses = await Expense.find({ relatedPayment: payment._id, isAutoGenerated: true });
      for (const expense of paymentExpenses) {
        // Revert cash register balance for each expense
        if (expense.cashRegister) {
          await CashRegister.findByIdAndUpdate(expense.cashRegister, {
            $inc: { balance: expense.amount }
          });
        }
      }
      await Expense.deleteMany({ relatedPayment: payment._id, isAutoGenerated: true });
    }
    // Delete all related payments
    await Payment.deleteMany({ paymentPlan: paymentPlan._id });

    // 2. Revert student balance (the initial debt added when payment plan was created)
    if (paymentPlan.student) {
      await Student.findByIdAndUpdate(paymentPlan.student, {
        $inc: { balance: -paymentPlan.discountedAmount }
      });
    }

    // 3. Finally delete the payment plan
    await PaymentPlan.findByIdAndDelete(req.params.id);

    // Log activity
    await ActivityLog.create({
      user: req.body?.deletedBy || 'System',
      action: 'delete',
      entity: 'PaymentPlan',
      entityId: paymentPlan._id,
      description: `Ödeme planı ve ilgili kayıtlar silindi`,
      institution: paymentPlan.institution,
      season: paymentPlan.season
    });

    res.json({ message: 'Ödeme planı ve ilgili kayıtlar silindi' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Refund installment
router.post('/:id/refund-installment', async (req, res) => {
  try {
    const { installmentNumber, refundCashRegisterId, refundReason } = req.body;

    const paymentPlan = await PaymentPlan.findById(req.params.id)
      .populate('student', 'firstName lastName');

    if (!paymentPlan) {
      return res.status(404).json({ message: 'Ödeme planı bulunamadı' });
    }

    const installment = paymentPlan.installments.find(
      inst => inst.installmentNumber === installmentNumber
    );

    if (!installment) {
      return res.status(404).json({ message: 'Taksit bulunamadı' });
    }

    if (!installment.isPaid) {
      return res.status(400).json({ message: 'Bu taksit henüz ödenmemiş' });
    }

    const refundAmount = installment.paidAmount || 0;

    // Find related payment for this installment
    const relatedPayment = await Payment.findOne({
      paymentPlan: paymentPlan._id,
      'installmentNumber': installmentNumber
    });

    if (relatedPayment) {
      // Mark payment as refunded
      relatedPayment.isRefunded = true;
      relatedPayment.refundDate = new Date();
      relatedPayment.refundReason = refundReason || 'Taksit iadesi';
      await relatedPayment.save();

      // Revert cash register balance (remove money from where it was added)
      if (relatedPayment.cashRegister) {
        await CashRegister.findByIdAndUpdate(relatedPayment.cashRegister, {
          $inc: { balance: -refundAmount }
        });
      }

      // Delete related auto-generated expenses (commission, VAT)
      const relatedExpenses = await Expense.find({
        relatedPayment: relatedPayment._id,
        isAutoGenerated: true
      });

      for (const expense of relatedExpenses) {
        // Revert expense effect on cash register
        if (expense.cashRegister) {
          await CashRegister.findByIdAndUpdate(expense.cashRegister, {
            $inc: { balance: expense.amount }
          });
        }
        await Expense.findByIdAndDelete(expense._id);
      }
    }

    // Add money to refund cash register (if specified)
    if (refundCashRegisterId) {
      await CashRegister.findByIdAndUpdate(refundCashRegisterId, {
        $inc: { balance: -refundAmount }
      });

      // Create refund expense record
      const refundExpense = new Expense({
        category: 'İade',
        amount: refundAmount,
        description: `${paymentPlan.student.firstName} ${paymentPlan.student.lastName} - ${installmentNumber}. taksit iadesi${refundReason ? ': ' + refundReason : ''}`,
        expenseDate: new Date(),
        cashRegister: refundCashRegisterId,
        isAutoGenerated: true,
        relatedStudent: paymentPlan.student._id,
        season: paymentPlan.season,
        institution: paymentPlan.institution,
        createdBy: req.body.createdBy
      });

      await refundExpense.save();
    }

    // Revert student balance (add back the debt)
    await Student.findByIdAndUpdate(paymentPlan.student._id || paymentPlan.student, {
      $inc: { balance: refundAmount }
    });

    // Reset installment status
    installment.isPaid = false;
    installment.paidAmount = 0;
    installment.paidDate = null;
    installment.isInvoiced = false;

    // Update payment plan totals
    paymentPlan.paidAmount = Math.max(0, (paymentPlan.paidAmount || 0) - refundAmount);
    paymentPlan.remainingAmount = paymentPlan.discountedAmount - paymentPlan.paidAmount;
    paymentPlan.isCompleted = false;

    await paymentPlan.save();

    // Log activity
    await ActivityLog.create({
      user: req.body.createdBy || 'System',
      action: 'update',
      entity: 'PaymentPlan',
      entityId: paymentPlan._id,
      description: `${installmentNumber}. taksit iade edildi (${refundAmount} TL)${refundReason ? ' - Sebep: ' + refundReason : ''}`,
      institution: paymentPlan.institution,
      season: paymentPlan.season
    });

    const populatedPaymentPlan = await PaymentPlan.findById(paymentPlan._id)
      .populate('institution', 'name')
      .populate('season', 'name startDate endDate')
      .populate('student', 'firstName lastName')
      .populate('course', 'name');

    res.json({
      message: `${installmentNumber}. taksit başarıyla iade edildi`,
      paymentPlan: populatedPaymentPlan
    });
  } catch (error) {
    console.error('Error refunding installment:', error);
    res.status(400).json({ message: error.message });
  }
});

module.exports = router;
