const express = require('express');
const router = express.Router();
const Payment = require('../models/Payment');
const Expense = require('../models/Expense');
const Student = require('../models/Student');
const CashRegister = require('../models/CashRegister');
const ActivityLog = require('../models/ActivityLog');

// Get all payments with filtering
router.get('/', async (req, res) => {
  try {
    const { institutionId, seasonId, studentId, cashRegisterId, paymentType, startDate, endDate } = req.query;
    const filter = {};

    if (institutionId) filter.institution = institutionId;
    if (seasonId) filter.season = seasonId;
    if (studentId) filter.student = studentId;
    if (cashRegisterId) filter.cashRegister = cashRegisterId;
    if (paymentType) filter.paymentType = paymentType;

    if (startDate && endDate) {
      filter.paymentDate = {
        $gte: new Date(startDate),
        $lte: new Date(endDate)
      };
    }

    const payments = await Payment.find(filter)
      .populate('institution', 'name')
      .populate('season', 'name startDate endDate')
      .populate('student', 'firstName lastName studentId')
      .populate('course', 'name')
      .populate('cashRegister', 'name')
      .sort({ paymentDate: -1 });

    res.json(payments);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Get payment by ID
router.get('/:id', async (req, res) => {
  try {
    const payment = await Payment.findById(req.params.id)
      .populate('institution', 'name')
      .populate('season', 'name startDate endDate')
      .populate('student', 'firstName lastName studentId')
      .populate('course', 'name')
      .populate('cashRegister', 'name');

    if (!payment) {
      return res.status(404).json({ message: 'Ödeme bulunamadı' });
    }
    res.json(payment);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Create payment
router.post('/', async (req, res) => {
  try {
    // Validate foreign keys
    if (req.body.student) {
      const studentExists = await Student.exists({ _id: req.body.student });
      if (!studentExists) {
        return res.status(404).json({ message: 'Öğrenci bulunamadı' });
      }
    }

    if (req.body.cashRegister) {
      const cashRegisterExists = await CashRegister.exists({ _id: req.body.cashRegister });
      if (!cashRegisterExists) {
        return res.status(404).json({ message: 'Kasa bulunamadı' });
      }
    }

    const payment = new Payment(req.body);
    const newPayment = await payment.save();

    // Update student balance
    if (newPayment.student) {
      await Student.findByIdAndUpdate(newPayment.student, {
        $inc: { balance: -newPayment.amount }
      });
    }

    // Update cash register balance
    if (newPayment.cashRegister) {
      await CashRegister.findByIdAndUpdate(newPayment.cashRegister, {
        $inc: { balance: newPayment.amount }
      });
    }

    // Log activity
    await ActivityLog.create({
      user: req.body.createdBy || 'System',
      action: 'create',
      entity: 'Payment',
      entityId: newPayment._id,
      description: `Yeni ödeme kaydı: ${newPayment.amount} TL (${newPayment.paymentType})`,
      institution: newPayment.institution,
      season: newPayment.season
    });

    const populatedPayment = await Payment.findById(newPayment._id)
      .populate('institution', 'name')
      .populate('season', 'name startDate endDate')
      .populate('student', 'firstName lastName studentId')
      .populate('course', 'name')
      .populate('cashRegister', 'name');

    res.status(201).json(populatedPayment);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// Update payment
router.put('/:id', async (req, res) => {
  try {
    const oldPayment = await Payment.findById(req.params.id);
    if (!oldPayment) {
      return res.status(404).json({ message: 'Ödeme bulunamadı' });
    }

    // Check if payment has related auto-generated expenses (VAT, commission)
    const relatedExpenseCount = await Expense.countDocuments({
      relatedPayment: req.params.id,
      isAutoGenerated: true
    });

    if (relatedExpenseCount > 0) {
      return res.status(400).json({
        message: 'İlişkili otomatik gider kayıtları olan ödemeler güncellenemez. Lütfen ödemeyi silip yeniden oluşturun.'
      });
    }

    // Revert old payment effects
    if (oldPayment.student) {
      await Student.findByIdAndUpdate(oldPayment.student, {
        $inc: { balance: oldPayment.amount }
      });
    }
    if (oldPayment.cashRegister) {
      await CashRegister.findByIdAndUpdate(oldPayment.cashRegister, {
        $inc: { balance: -oldPayment.amount }
      });
    }

    const payment = await Payment.findByIdAndUpdate(
      req.params.id,
      { ...req.body, updatedBy: req.body.updatedBy },
      { new: true }
    ).populate('institution', 'name')
     .populate('season', 'name startDate endDate')
     .populate('student', 'firstName lastName studentId')
     .populate('course', 'name')
     .populate('cashRegister', 'name');

    // Apply new payment effects
    if (payment.student) {
      await Student.findByIdAndUpdate(payment.student, {
        $inc: { balance: -payment.amount }
      });
    }
    if (payment.cashRegister) {
      await CashRegister.findByIdAndUpdate(payment.cashRegister, {
        $inc: { balance: payment.amount }
      });
    }

    // Log activity
    await ActivityLog.create({
      user: req.body.updatedBy || 'System',
      action: 'update',
      entity: 'Payment',
      entityId: payment._id,
      description: `Ödeme güncellendi: ${payment.amount} TL`,
      institution: payment.institution._id,
      season: payment.season._id
    });

    res.json(payment);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
});

// Refund payment
router.post('/:id/refund', async (req, res) => {
  try {
    const { refundCashRegisterId, refundAmount, refundFullCommission } = req.body;

    const payment = await Payment.findById(req.params.id)
      .populate('student', 'firstName lastName')
      .populate('cashRegister', 'name');

    if (!payment) {
      return res.status(404).json({ message: 'Ödeme bulunamadı' });
    }

    if (payment.isRefunded) {
      return res.status(400).json({ message: 'Bu ödeme zaten iade edilmiş' });
    }

    const actualRefundAmount = refundAmount || payment.amount;

    // Validate refund amount
    if (actualRefundAmount <= 0) {
      return res.status(400).json({ message: 'İade tutarı sıfırdan büyük olmalıdır' });
    }

    if (actualRefundAmount > payment.amount) {
      return res.status(400).json({ message: `İade tutarı, ödeme tutarından (₺${payment.amount}) fazla olamaz` });
    }

    // Create refund expense
    const refundExpense = new Expense({
      category: 'Ödeme İadesi',
      amount: actualRefundAmount,
      description: `${payment.student.firstName} ${payment.student.lastName} - ${payment.installmentNumber ? payment.installmentNumber + '. taksit' : 'ödeme'} iadesi`,
      expenseDate: new Date(),
      cashRegister: refundCashRegisterId,
      isAutoGenerated: true,
      relatedPayment: payment._id,
      season: payment.season,
      institution: payment.institution,
      createdBy: req.body.createdBy
    });

    await refundExpense.save();

    // Deduct refund amount from cash register
    await CashRegister.findByIdAndUpdate(refundCashRegisterId, {
      $inc: { balance: -actualRefundAmount }
    });

    // Update student balance (add back the refunded amount)
    await Student.findByIdAndUpdate(payment.student._id, {
      $inc: { balance: actualRefundAmount }
    });

    // If payment was invoiced, reverse the VAT expense
    if (payment.isInvoiced && payment.vat && payment.vat.amount > 0) {
      // Find the VAT expense related to this payment
      const vatExpense = await Expense.findOne({
        relatedPayment: payment._id,
        category: 'KDV',
        isAutoGenerated: true
      });

      if (vatExpense) {
        // Reverse the VAT expense by adding it back to cash register
        await CashRegister.findByIdAndUpdate(vatExpense.cashRegister, {
          $inc: { balance: vatExpense.amount }
        });

        // Delete the VAT expense
        await Expense.findByIdAndDelete(vatExpense._id);
      }
    }

    // Note: Credit card commission is NOT refunded (stays as expense)

    // Mark payment as refunded
    payment.isRefunded = true;
    payment.refundDate = new Date();
    payment.refundAmount = actualRefundAmount;
    payment.refundCashRegister = refundCashRegisterId;
    await payment.save();

    // Log activity
    await ActivityLog.create({
      user: req.body.createdBy || 'System',
      action: 'refund',
      entity: 'Payment',
      entityId: payment._id,
      description: `Ödeme iade edildi: ${actualRefundAmount} TL`,
      institution: payment.institution,
      season: payment.season
    });

    res.json({ message: 'Ödeme başarıyla iade edildi', payment });
  } catch (error) {
    console.error('Error refunding payment:', error);
    res.status(500).json({ message: error.message });
  }
});

// Delete payment
router.delete('/:id', async (req, res) => {
  try {
    const payment = await Payment.findById(req.params.id);
    if (!payment) {
      return res.status(404).json({ message: 'Ödeme bulunamadı' });
    }

    // Revert payment effects
    if (payment.student) {
      await Student.findByIdAndUpdate(payment.student, {
        $inc: { balance: payment.amount }
      });
    }
    if (payment.cashRegister) {
      await CashRegister.findByIdAndUpdate(payment.cashRegister, {
        $inc: { balance: -payment.amount }
      });
    }

    // Delete related auto-generated expenses (commission, VAT) and revert their effects
    const relatedExpenses = await Expense.find({ relatedPayment: payment._id, isAutoGenerated: true });
    for (const expense of relatedExpenses) {
      // Revert cash register balance for each expense
      if (expense.cashRegister) {
        await CashRegister.findByIdAndUpdate(expense.cashRegister, {
          $inc: { balance: expense.amount }
        });
      }
    }
    // Delete the expenses
    await Expense.deleteMany({ relatedPayment: payment._id, isAutoGenerated: true });

    await Payment.findByIdAndDelete(req.params.id);

    // Log activity
    await ActivityLog.create({
      user: req.body?.deletedBy || 'System',
      action: 'delete',
      entity: 'Payment',
      entityId: payment._id,
      description: `Ödeme silindi: ${payment.amount} TL`,
      institution: payment.institution,
      season: payment.season
    });

    res.json({ message: 'Ödeme silindi' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Data repair endpoint - Fix inconsistent payment data
// This should only be used by admins to fix data issues
router.post('/repair/recalculate-cash-register/:cashRegisterId', async (req, res) => {
  try {
    const { cashRegisterId } = req.params;
    const { startingBalance = 0 } = req.body;

    const cashRegister = await CashRegister.findById(cashRegisterId);
    if (!cashRegister) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }

    // Calculate total income from completed, non-refunded payments
    const payments = await Payment.find({
      cashRegister: cashRegisterId,
      isRefunded: { $ne: true }
    });

    let totalIncome = 0;
    for (const payment of payments) {
      // Only count completed payments that are not refunded
      if (!payment.isRefunded && payment.status !== 'refunded') {
        totalIncome += payment.amount || 0;
      }
    }

    // Calculate total expenses
    const expenses = await Expense.find({
      cashRegister: cashRegisterId
    });

    let totalExpenses = 0;
    for (const expense of expenses) {
      totalExpenses += expense.amount || 0;
    }

    // Calculate correct balance
    const correctBalance = startingBalance + totalIncome - totalExpenses;

    // Get current balance for comparison
    const currentBalance = cashRegister.balance || 0;

    // Update cash register with correct balance
    await CashRegister.findByIdAndUpdate(cashRegisterId, {
      balance: correctBalance
    });

    res.json({
      message: 'Kasa bakiyesi yeniden hesaplandı',
      details: {
        cashRegisterName: cashRegister.name,
        startingBalance: startingBalance,
        totalIncome: totalIncome,
        totalExpenses: totalExpenses,
        correctBalance: correctBalance,
        previousBalance: currentBalance,
        difference: correctBalance - currentBalance
      }
    });
  } catch (error) {
    console.error('Error repairing cash register:', error);
    res.status(500).json({ message: error.message });
  }
});

// Fix payment status for all payments that don't have status field
router.post('/repair/fix-payment-statuses', async (req, res) => {
  try {
    // Find all payments without status field or with undefined status
    const paymentsWithoutStatus = await Payment.find({
      $or: [
        { status: { $exists: false } },
        { status: null }
      ]
    });

    let updatedCount = 0;
    for (const payment of paymentsWithoutStatus) {
      // If payment is refunded, set status to refunded
      // Otherwise, set to completed
      const newStatus = payment.isRefunded ? 'refunded' : 'completed';
      await Payment.findByIdAndUpdate(payment._id, { status: newStatus });
      updatedCount++;
    }

    res.json({
      message: `${updatedCount} ödemenin durumu güncellendi`,
      updatedCount: updatedCount
    });
  } catch (error) {
    console.error('Error fixing payment statuses:', error);
    res.status(500).json({ message: error.message });
  }
});

// ===========================================
// DATABASE REPAIR ENDPOINTS
// ===========================================

// List all cash registers with their balances
router.get('/repair/list-cash-registers', async (req, res) => {
  try {
    const { institutionId } = req.query;
    const filter = institutionId ? { institution: institutionId } : {};

    const cashRegisters = await CashRegister.find(filter)
      .populate('institution', 'name')
      .populate('season', 'name');

    res.json({
      count: cashRegisters.length,
      cashRegisters: cashRegisters.map(cr => ({
        id: cr._id,
        name: cr.name,
        balance: cr.balance,
        initialBalance: cr.initialBalance || 0,
        institution: cr.institution?.name,
        season: cr.season?.name,
        isActive: cr.isActive
      }))
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// List all students with their balances
router.get('/repair/list-students', async (req, res) => {
  try {
    const { institutionId, seasonId } = req.query;
    const filter = {};
    if (institutionId) filter.institution = institutionId;
    if (seasonId) filter.season = seasonId;

    const students = await Student.find(filter)
      .populate('institution', 'name')
      .populate('season', 'name')
      .sort({ lastName: 1, firstName: 1 });

    res.json({
      count: students.length,
      students: students.map(s => ({
        id: s._id,
        studentId: s.studentId,
        name: `${s.firstName} ${s.lastName}`,
        balance: s.balance,
        status: s.status,
        institution: s.institution?.name,
        season: s.season?.name
      }))
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Reset cash register balance to specific value
router.post('/repair/reset-cash-register-balance', async (req, res) => {
  try {
    const { cashRegisterId, cashRegisterName, newBalance = 0 } = req.body;

    let cashRegister;
    if (cashRegisterId) {
      cashRegister = await CashRegister.findById(cashRegisterId);
    } else if (cashRegisterName) {
      cashRegister = await CashRegister.findOne({ name: { $regex: cashRegisterName, $options: 'i' } });
    }

    if (!cashRegister) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }

    const oldBalance = cashRegister.balance;
    cashRegister.balance = newBalance;
    await cashRegister.save();

    res.json({
      message: 'Kasa bakiyesi güncellendi',
      cashRegister: {
        id: cashRegister._id,
        name: cashRegister.name,
        oldBalance: oldBalance,
        newBalance: newBalance
      }
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Reset student balance to specific value
router.post('/repair/reset-student-balance', async (req, res) => {
  try {
    const { studentId, studentName, newBalance = 0 } = req.body;

    let student;
    if (studentId) {
      student = await Student.findById(studentId);
    } else if (studentName) {
      // Search by name (partial match)
      const nameParts = studentName.split(' ');
      if (nameParts.length >= 2) {
        student = await Student.findOne({
          firstName: { $regex: nameParts[0], $options: 'i' },
          lastName: { $regex: nameParts.slice(1).join(' '), $options: 'i' }
        });
      } else {
        student = await Student.findOne({
          $or: [
            { firstName: { $regex: studentName, $options: 'i' } },
            { lastName: { $regex: studentName, $options: 'i' } }
          ]
        });
      }
    }

    if (!student) {
      return res.status(404).json({ message: 'Öğrenci bulunamadı' });
    }

    const oldBalance = student.balance;
    student.balance = newBalance;
    await student.save();

    res.json({
      message: 'Öğrenci bakiyesi güncellendi',
      student: {
        id: student._id,
        name: `${student.firstName} ${student.lastName}`,
        oldBalance: oldBalance,
        newBalance: newBalance
      }
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Delete orphaned payments (payments with no student or deleted payment plan)
router.post('/repair/cleanup-orphaned-records', async (req, res) => {
  try {
    const { institutionId, dryRun = true } = req.body;
    const filter = institutionId ? { institution: institutionId } : {};

    const results = {
      orphanedPayments: [],
      orphanedExpenses: [],
      deletedPayments: 0,
      deletedExpenses: 0
    };

    // Find payments with non-existent students
    const payments = await Payment.find(filter);
    for (const payment of payments) {
      if (payment.student) {
        const studentExists = await Student.exists({ _id: payment.student });
        if (!studentExists) {
          results.orphanedPayments.push({
            id: payment._id,
            amount: payment.amount,
            reason: 'Student does not exist'
          });
        }
      }
    }

    // Find expenses related to payments that don't exist
    const expenses = await Expense.find({ ...filter, relatedPayment: { $exists: true, $ne: null } });
    for (const expense of expenses) {
      const paymentExists = await Payment.exists({ _id: expense.relatedPayment });
      if (!paymentExists) {
        results.orphanedExpenses.push({
          id: expense._id,
          category: expense.category,
          amount: expense.amount,
          reason: 'Related payment does not exist'
        });
      }
    }

    if (!dryRun) {
      // Delete orphaned records
      for (const orphan of results.orphanedPayments) {
        await Payment.findByIdAndDelete(orphan.id);
        results.deletedPayments++;
      }
      for (const orphan of results.orphanedExpenses) {
        await Expense.findByIdAndDelete(orphan.id);
        results.deletedExpenses++;
      }
    }

    res.json({
      message: dryRun ? 'Dry run completed - no changes made' : 'Cleanup completed',
      dryRun: dryRun,
      results: results
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// Full data repair - recalculate all balances from scratch
router.post('/repair/full-recalculate', async (req, res) => {
  try {
    const { institutionId, dryRun = true } = req.body;

    if (!institutionId) {
      return res.status(400).json({ message: 'institutionId gerekli' });
    }

    const results = {
      cashRegisters: [],
      students: []
    };

    // Recalculate all cash register balances
    const cashRegisters = await CashRegister.find({ institution: institutionId });
    for (const cr of cashRegisters) {
      // Get all payments for this cash register
      const payments = await Payment.find({
        cashRegister: cr._id,
        isRefunded: { $ne: true }
      });

      let totalIncome = 0;
      for (const p of payments) {
        totalIncome += p.amount || 0;
      }

      // Get all expenses for this cash register
      const expenses = await Expense.find({ cashRegister: cr._id });
      let totalExpenses = 0;
      let manualIncome = 0;

      for (const e of expenses) {
        // Check if this is a manual income entry
        if (e.isManualIncome === true || e.category === 'Kasa Giriş (Manuel)') {
          // Manual income entries add to balance, not subtract
          manualIncome += e.amount || 0;
        } else {
          // Regular expenses subtract from balance
          totalExpenses += e.amount || 0;
        }
      }

      // Total income includes payments + manual income entries
      totalIncome += manualIncome;

      const calculatedBalance = (cr.initialBalance || 0) + totalIncome - totalExpenses;
      const difference = calculatedBalance - (cr.balance || 0);

      results.cashRegisters.push({
        id: cr._id,
        name: cr.name,
        currentBalance: cr.balance,
        calculatedBalance: calculatedBalance,
        totalIncome: totalIncome,
        totalExpenses: totalExpenses,
        manualIncome: manualIncome,
        difference: difference
      });

      if (!dryRun && difference !== 0) {
        cr.balance = calculatedBalance;
        await cr.save();
      }
    }

    // Recalculate all student balances
    const students = await Student.find({ institution: institutionId });
    const PaymentPlan = require('../models/PaymentPlan');

    for (const student of students) {
      // Get all payment plans for this student
      const paymentPlans = await PaymentPlan.find({ student: student._id });

      let totalDebt = 0;
      let totalPaid = 0;

      for (const plan of paymentPlans) {
        totalDebt += plan.totalAmount || 0;

        // Sum up paid installments
        if (plan.installments && plan.installments.length > 0) {
          for (const inst of plan.installments) {
            if (inst.status === 'paid') {
              totalPaid += inst.paidAmount || inst.amount || 0;
            }
          }
        }
      }

      // Also check for standalone payments not linked to payment plans
      const standalonePayments = await Payment.find({
        student: student._id,
        paymentPlan: { $exists: false },
        isRefunded: { $ne: true }
      });

      for (const p of standalonePayments) {
        totalPaid += p.amount || 0;
      }

      const calculatedBalance = totalDebt - totalPaid;
      const difference = calculatedBalance - (student.balance || 0);

      results.students.push({
        id: student._id,
        name: `${student.firstName} ${student.lastName}`,
        currentBalance: student.balance,
        calculatedBalance: calculatedBalance,
        totalDebt: totalDebt,
        totalPaid: totalPaid,
        difference: difference
      });

      if (!dryRun && difference !== 0) {
        student.balance = calculatedBalance;
        await student.save();
      }
    }

    res.json({
      message: dryRun ? 'Dry run completed - no changes made' : 'Full recalculation completed',
      dryRun: dryRun,
      results: results
    });
  } catch (error) {
    console.error('Error in full recalculate:', error);
    res.status(500).json({ message: error.message });
  }
});

// Diagnostic endpoint - Check data consistency for a cash register
router.get('/diagnostic/cash-register/:cashRegisterId', async (req, res) => {
  try {
    const { cashRegisterId } = req.params;

    const cashRegister = await CashRegister.findById(cashRegisterId);
    if (!cashRegister) {
      return res.status(404).json({ message: 'Kasa bulunamadı' });
    }

    // Get all payments for this cash register
    const payments = await Payment.find({ cashRegister: cashRegisterId })
      .populate('student', 'firstName lastName')
      .sort({ paymentDate: -1 });

    // Get all expenses for this cash register
    const expenses = await Expense.find({ cashRegister: cashRegisterId })
      .sort({ expenseDate: -1 });

    // Calculate expected balance
    let calculatedIncome = 0;
    let refundedAmount = 0;
    const paymentDetails = [];

    for (const payment of payments) {
      const detail = {
        id: payment._id,
        student: payment.student ? `${payment.student.firstName} ${payment.student.lastName}` : 'N/A',
        amount: payment.amount,
        status: payment.status || 'undefined',
        isRefunded: payment.isRefunded,
        date: payment.paymentDate,
        installmentNumber: payment.installmentNumber
      };
      paymentDetails.push(detail);

      if (payment.isRefunded) {
        refundedAmount += payment.amount || 0;
      } else {
        calculatedIncome += payment.amount || 0;
      }
    }

    let calculatedExpenses = 0;
    const expenseDetails = [];
    for (const expense of expenses) {
      expenseDetails.push({
        id: expense._id,
        category: expense.category,
        amount: expense.amount,
        description: expense.description,
        date: expense.expenseDate,
        isAutoGenerated: expense.isAutoGenerated
      });
      calculatedExpenses += expense.amount || 0;
    }

    const expectedBalance = (cashRegister.initialBalance || 0) + calculatedIncome - calculatedExpenses;

    res.json({
      cashRegister: {
        name: cashRegister.name,
        currentBalance: cashRegister.balance,
        initialBalance: cashRegister.initialBalance || 0
      },
      calculated: {
        totalIncome: calculatedIncome,
        totalExpenses: calculatedExpenses,
        refundedPayments: refundedAmount,
        expectedBalance: expectedBalance,
        discrepancy: cashRegister.balance - expectedBalance
      },
      payments: paymentDetails,
      expenses: expenseDetails
    });
  } catch (error) {
    console.error('Error running diagnostic:', error);
    res.status(500).json({ message: error.message });
  }
});

module.exports = router;
