const mongoose = require('mongoose');

const expenseSchema = new mongoose.Schema({
  // Gider kategorisi
  category: {
    type: String,
    required: true,
    enum: [
      'Kira',
      'Elektrik',
      'Su',
      'Doğalgaz',
      'İnternet',
      'Telefon',
      'Kırtasiye',
      'Temizlik Malzemeleri',
      'Dekorasyon ve Sahne Malzemeleri',
      'Kostüm ve Aksesuar',
      'Eğitmen Ödemesi',
      'KDV',
      'Kredi Kartı Komisyonu',
      'Çay/Kahve',
      'Yemek',
      'Ulaşım',
      'Sigorta',
      'Reklam ve Tanıtım',
      'Web Hosting/Domain',
      'Yazılım Lisansı',
      'Müzik/Ses Sistemi',
      'Işık Ekipmanları',
      'Kamera/Fotoğraf',
      'Ofis Malzemeleri',
      'Bakım Onarım',
      'Vergi',
      'Diğer'
    ]
  },
  // Gider tutarı
  amount: {
    type: Number,
    required: true
  },
  // Gider açıklaması
  description: {
    type: String,
    required: true
  },
  // Gider tarihi
  expenseDate: {
    type: Date,
    required: true,
    default: Date.now
  },
  // Hangi kasadan ödendi
  cashRegister: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'CashRegister',
    required: true
  },
  // Fatura/belge
  invoice: {
    hasInvoice: {
      type: Boolean,
      default: false
    },
    invoiceNumber: String,
    invoiceFile: String // path to uploaded file
  },
  // Eğer eğitmen ödemesiyse
  instructor: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Instructor'
  },
  // Otomatik oluşturuldu mu (KDV, komisyon gibi)
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  // İlişkili ödeme (eğer KDV veya komisyon gideriyse)
  relatedPayment: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Payment'
  },
  season: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Season',
    required: true
  },
  institution: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Institution',
    required: true
  },
  notes: String,
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  },
  createdBy: String,
  updatedBy: String
});

expenseSchema.pre('save', function(next) {
  this.updatedAt = Date.now();
  next();
});

module.exports = mongoose.model('Expense', expenseSchema);
